### PR TITLE
docs: add overview for implemented requests

### PR DESCRIPTION
**Pull request by Nerixyz**
~~I'll rebase this once https://github.com/twitch-rs/twitch_api/pull/359 is merged.~~

This adds a script to generate an overview over the implemented requests and helpers. It requires Rust nightly. On a high level, the script reads the Twitch docs and matches the endpoints to the implemented endpoints in this crate.

```sh
cargo (+nightly) xtask overview
```

CI will check if the docs are up-to-date and provide a diff if they're not (`--check`).

Towards #330.

### CODE REVIEW

**Comment by Emilgardis** [comment]
would it be possible to do this for eventsub too?

**Comment by Nerixyz** [comment]
> would it be possible to do this for eventsub too?

I've added an overview for eventsub, but the types are quite long:

firefox_2024-04-15_21-26-21

**Comment by Nerixyz** [comment]
Updated it to Rust, so people don't need to install Deno anymore. The only downside is that the code is much larger. On the upside, this should give us schema updates of the JSON format Rustdoc uses. I kept the previous commit for reference, but that should be squashed before a merge.

**Review by Emilgardis — APPROVED** [review]
This looks ~~good~~ great, feel free to merge

**Pull request merged**
