### PR TITLE
feat: Add title and description to chat badges

### PR DESCRIPTION
**Pull request by jameshi16**
https://dev.twitch.tv/docs/api/reference/#get-channel-chat-badges
https://dev.twitch.tv/docs/api/reference/#get-global-chat-badges

Added title and description to the chat badges. I needed it for one of my projects, so I figured I may as well contribute back.

### CODE REVIEW

**Review by Emilgardis — CHANGES_REQUESTED** [review]
Thank you! Tests needs to include these fields also

https://github.com/jameshi16/twitch_api/blob/76c33b5721773a7c3f9aad77a83e5b2feb632f57/src/helix/endpoints/chat/get_channel_chat_badges.rs#L88
and
https://github.com/jameshi16/twitch_api/blob/76c33b5721773a7c3f9aad77a83e5b2feb632f57/src/helix/endpoints/chat/get_global_chat_badges.rs#L76


Related change by twitch: https://discuss.dev.twitch.com/t/legacy-badges-endpoint-shutdown-details-and-timeline-june-2023/44621

Feel free to also add `click_url` and `click_action`

A minor note, `badges` got a typo in the commit :D but that doesn't matter

**Comment by jameshi16** [comment]
rebased so you only get one commit in your history :)

I won't implement `click_url` and `click_action` for now if that's ok

**Comment by Emilgardis** [comment]
perfect, one last thing I forgot, can you add a changelog entry :)

**Comment by jameshi16** [comment]
no problem :))

could you add a small note into the `CONTRIBUTING.md` for updating the changelogs? that'll help future contributors i think

**Review by Emilgardis — APPROVED** [review]
Thank you!

**Pull request merged**
